config/routes.rb
Rails.application.routes.draw do
  root to: 'tweets#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'users/signup', to: 'users#new'
  resources :users, except: :new

  resources :tweets do
    resources :comments
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
  belongs_to :user

  validates :body, presence: true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :body, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  has_many :tweets, dependent: :destroy
  has_many :comments, dependent: :destroy

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  before_save :email_to_downcase

  validates :name, presence: true, length: { maximum: 255 }
  validates :email, presence: true, length: { maximum: 50 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true

  private

  def email_to_downcase
    self.email = email.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    session_notice(:danger, 'You have to be logged in!', login_path) unless logged_in?
    @tweet = Tweet.find(params[:tweet_id])
    @comment = @tweet.comments.build
  end

  def create
    @tweet = Tweet.find(params[:tweet_id])
    @comment = @tweet.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to @tweet
    else
      render :new
    end
  end

  def edit
    session_notice(:danger, 'You have to be logged in!', login_path) unless logged_in?
    @comment = Comment.find(params[:id])
    if logged_in?
      session_notice(:danger, 'Wrong User') unless equal_with_current_user?(@comment.user)
    end
    @tweet = @comment.tweet
  end

  def update
    @comment = Comment.find(params[:id])
    @tweet = @comment.tweet

    if @comment.update(comment_params)
      redirect_to @tweet
    else
      render :edit
    end
  end

  def destroy
    session_notice(:danger, 'You must be logged in!', login_path) unless logged_in?
    comment = Comment.find(params[:id])
    if equal_with_current_user?(comment.user)
      comment.destroy
      redirect_to comment.tweet
    else
      session_notice(:danger, 'Wrong User')
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    session_notice('warning', 'Already logged in!') if logged_in?
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      log_in(user)
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all.order(created_at: :desc)
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comments = @tweet.comments.order(created_id: :desc)
  end

  def new
    session_notice(:danger, 'You have to be logged in!') unless logged_in?
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user

    if @tweet.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    session_notice(:danger, 'You have to be logged in!') unless logged_in?
    @tweet = Tweet.find(params[:id])
    if logged_in?
      session_notice(:danger, 'Wrong User') unless equal_with_current_user?(@tweet.user)
    end
  end

  def update
    @tweet = Tweet.find(params[:id])

    if @tweet.update(tweet_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    session_notice(:danger, 'You have to be logged in!') unless logged_in?
    tweet = Tweet.find(params[:id])
    if equal_with_current_user?(tweet.user)
      tweet.destroy
      redirect_to tweets_path
    else
      session_notice(:danger, 'Wrong User')
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    session_notice(:warning, 'Already logged in!') if logged_in?
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    current_user.present?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def session_notice(type, message, path = root_path)
    flash[type.to_sym] = message
    redirect_to path and return
  end

  def equal_with_current_user?(other_user)
    current_user == other_user
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
    <article class="media">
    <figure class="media-left">
      <p class="image is-64x64">
        <img src="https://bulma.io/images/placeholders/128x128.png">
      </p>
    </figure>
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= comment.user.name %></strong> <small><%= time_ago_in_words(comment.created_at) %> ago </small>
          <br>
          <%= comment.body %>
        </p>
      </div>
      <nav class="level is-mobile">
        <% if equal_with_current_user?(comment.user) %>
          <div class="level-left">
            <%= link_to edit_tweet_comment_path(comment.tweet, comment), class: "level-item" do %>
              <span class="icon is-small"><i class="fas fa-edit"></i></span>
            <% end %>
            <%= link_to tweet_comment_path(comment.tweet, comment), method: :delete , class: "level-item", data: { confirm: "Are you sure you want to delete this comment?" } do %>
              <span class="icon is-small"><i class="fas fa-trash-alt"></i></span>
            <% end %>
          </div>
        <% end %>
      </nav>
    </div>
  </article>

app/views/comments/_form.html.erb
<% if comment.errors.any? %>
  <div id="error_explanation" class="notification is-warning">
    <p><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</p><br>
      <p>
        <% comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </p>
  </div>
<% end %>

<div class="media-content">
  <%= form_with model: [tweet, comment], local: true do |form| %>
    <div class="field">
      <p class="control">
        <%= form.text_area :body, class: "textarea", placeholder: "Add a comment..." %>
      </p>
    </div>
    <div class="field is-grouped">
    <nav class="level">
      <div class="level-left">
        <div class="level-item">
           <%= form.submit submit, class: 'button is-info'%>
        </div>
        <div class="level-item">
          <%= link_to "Back", root_path, class: 'button is-info is-light' %>
        </div>
      </div>
      <div class="level-right">
        <div class="level-item">
          <label class="checkbox">
            <input type="checkbox"> Press enter to submit
          </label>
        </div>
      </div>
    </nav>
    <% end %>
  </div>

app/views/comments/edit.html.erb
<%= render 'form',
  tweet: @tweet,
  comment: @comment,
  heading: "Edit comment",
  submit: "Update" %>

app/views/comments/new.html.erb
<%= render 'form',
    tweet: @tweet,
    comment: @comment,
    submit: 'Post Comment'
%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <%= render 'shared/nav_bar' %>
    <div class="column is-6 is-offset-3">
    <%= render 'shared/flash' %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flash.html.erb
<div class="columns is-multiline">
  <% flash.each do |name, msg| -%>
    <div class="column is-8 is-offset-2">
      <div class="notification has-text-centered is-<%= name %>">
        <%= msg %>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_nav_bar.html.erb
 <nav class="navbar is-info">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-3" id="home-title">Twitter Clone</h1>
        <% end %>
      </div>

    <div id="navbarExample" class="navbar-menu">
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
            <% if logged_in? %>
              <%= link_to "New Tweet", new_tweet_path, class: "button is-info has-text-weight-bold" %>
              <%= link_to "Log Out", logout_path, method: :delete, class: "button is-info has-text-weight-bold" %>
            <% else %>
              <%= link_to "Log In", login_path, class: "button is-info has-text-weight-bold" %>
              <%= link_to "Sign Up", users_signup_path, class: "button is-info has-text-weight-bold" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
</nav>

app/views/tweets/_form.html.erb
<h1 class="is-size-3"><%= heading %></h1>

<% if tweet.errors.any? %>
  <div id="error_explanation" class="notification is-warning">
    <h2>
      <%= pluralize(tweet.errors.count, "error") %> prohibited
      this tweet from being saved:
    </h2>
    <ul>
      <% tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: tweet, local: true do |form| %>
  <div class="field">
    <div class="control">
      <%= form.text_area :body, class:'is-focused textarea',
        placeholder: 'Tweet content, max 140 characters.', autofocus: true %>
    </div>
  </div>
   <div class="field is-grouped">
    <div class="control">
      <%= form.submit submit, class: 'button is-info'%>
    </div>
    <div class="control">
      <%= link_to 'Cancel', cancel_path, class: 'button is-info is-light' %>
    </div>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<article class="media">
  <figure class="media-left">
    <p class="image is-64x64">
      <img src="https://bulma.io/images/placeholders/128x128.png">
    </p>
  </figure>
  <div class="media-content">
    <div class="content">
    <%= link_to tweet_path(tweet) do %>
      <p>
        <strong><%= tweet.user.name %></strong> <small>@<%= tweet.user.name.downcase %></small> <small><%= time_ago_in_words(tweet.created_at) %> ago</small>
        <br>
        <%= tweet.body %>
      </p>
      <% end %>
    </div>
    <nav class="level is-mobile">
      <div class="level-left">
        <%= link_to tweet_path(tweet), class: 'level-item' do%>
          <span class="icon is-small"><i class="fas fa-reply"></i></span>
        <% end %>
        <a class="level-item">
          <span class="icon is-small"><i class="fas fa-retweet"></i></span>
        </a>
        <a class="level-item">
          <span class="icon is-small"><i class="fas fa-heart"></i></span>
        </a>
      </div>
    </nav>
  </div>
  <div class="media-right">
   <%= link_to tweet_path(tweet), class: "link is-info" do%>
      <span class="icon is-small"><i class="fa fa-expand" aria-hidden="true"></i></span>
    <% end %>
    <% if logged_in? && equal_with_current_user?(tweet.user) %>
    <%= link_to edit_tweet_path(tweet), class: "link is-info" do%>
      <span class="icon is-small"><i class="fas fa-edit" aria-hidden="true"></i></span>
    <% end %>
    <% end %>
    <% if logged_in? && equal_with_current_user?(tweet.user) %>
    <%= link_to tweet_path(tweet), method: :delete, data: { confirm: "Are you sure you want to delete this tweet?" }, class: "link is-info" do %>
      <span class="icon is-small"><i class="fas fa-trash-alt" aria-hidden="true"></i></span>
    <% end %>
    <% end %>
  </div>
</article>

app/views/tweets/edit.html.erb
<%= render 'form',
tweet: @tweet,
comment: @comment,
submit: 'Update Tweet',
cancel_path: tweet_path(@tweet),
heading: 'Edit tweet' %>

app/views/tweets/index.html.erb
<div class="field is-grouped">
  <div class="control">
    <div class=" is-info">
      <i class="fab fa-twitter fa-3x"></i>
    </div>
  </div>
  <div class="control">
    <h1 class="is-size-3">Tweets Timeline</h1>
  </div>
</div>
<br>
 <%= render @tweets %>
 <footer class="footer">
  <div class="has-text-centered">
    <p>
      <strong>Twitter exercise</strong> by Alex. The source code is licensed
      <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. The website content
      is is for the purpose of code academy training provided by <a href="https://codeacademy.mk/">Code Academy MK</a>.
    </p>
  </div>
</footer>

app/views/tweets/new.html.erb
<%= render 'form',
tweet: @tweet,
comment: @comment,
submit: 'Publish Tweet',
cancel_path: root_path,
heading: 'Compose a new tweet' %>

app/views/tweets/show.html.erb
<article class="media">
  <figure class="media-left">
    <p class="image is-64x64">
      <img src="https://bulma.io/images/placeholders/128x128.png">
    </p>
  </figure>
  <div class="media-content">
    <div class="content">
      <p>
        <strong><%= @tweet.user.name %></strong> <small>@<%= @tweet.user.name.downcase %></small> <small><%= time_ago_in_words(@tweet.created_at) %> ago</small>
        <br>
        <%= @tweet.body %>
      </p>
    </div>
    <nav class="level is-mobile">
      <div class="level-left">
        <a class="level-item">
          <span class="icon is-small"><i class="fas fa-reply"></i></span>
        </a>
        <a class="level-item">
          <span class="icon is-small"><i class="fas fa-retweet"></i></span>
        </a>
        <a class="level-item">
          <span class="icon is-small"><i class="fas fa-heart"></i></span>
        </a>
      </div>
    </nav>
  </div>
  <div class="media-right">
    <%= link_to root_path do %>
      <span class="icon is-small is-info"><i class="fa fa-window-close fa-2x"></i></span>
    <% end %>
  </div>
</article>

<article class="media">
    <div class="media-content">
      <div class="content">
        <p><%= pluralize(@tweet.comments.count, 'Comment') %></p>
      </div>
    </div>
    <%# <% if local_assigns[:show] && logged_in? %>
      <%= link_to "New Comment", new_tweet_comment_path(@tweet), class: 'button is-info' %>
    <%# <% end %>
  </article>

  <%= render @tweet.comments %>

app/views/users/new.html.erb
<div class="section">
	<div class="container">
	<div class="card">
	<div class="card-content">
	<div class="columns is-centered">
		<div class="column is-4">
		<h2 class="title is-2">Sign Up</h2>

    <% if @user.errors.any? %>
      <div id="error_explanation" class="notification is-warning">
        <h2>
          <%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:
        </h2><br>
        <p>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </p>
      </div>
    <% end %>

		<%= form_with model: @user, local: true do |form| %>
	  <div class="field">
	  	<div class="control">
        <%= form.label :name, class: "label" %>
        <%= form.text_field :name, required: true, autofocus: true, class:"input", wrapper: false %>
	  	</div>
		</div>

		<div class="field">
	  	<div class="control">
        <%= form.label :email, class: "label" %>
        <%= form.email_field :email, required: true, class:"input", wrapper: false %>
	  	</div>
		</div>


		<div class="field">
			<div class="control">
        <%= form.label :password, class: "label" %>
				<%= form.password_field :password, required: true, class:"input", wrapper: false %>
			</div>
		</div>

		<div class="field">
			<div class="control">
        <%= form.label :password_confirmation, class: "label" %>
				<%= form.password_field :password_confirmation, required: true, class: "input", wrapper: false %>
			</div>
		</div>

		<div class="field is-grouped">
			  <div class="control">
		 		<%= form.submit "Sign up", class:"button is-info is-rounded" %>
		 	</div>
      <div class="control">
        <%= link_to "Cancel", tweets_path, class: 'button is-info is-light is-rounded' %>
      </div>
    </div>
		<% end %>
			<br />
		</div>
		</div>
	</div>
	</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-3">
      <h3><%= @user.name %></h3>
      <p><%= @user.email %></p>
      </div>
    </div>
  </div>
</div>